### ISSUE TITLE
Setup some sort of autobuild + release packaging with GitHub

### ISSUE THREAD

**Issue by xparq** [xparq/Out_of_Nothing#5]
@azitmentor, your hands-on CI expertise may come in handy here.

-> [README](https://github.com/lunakid/sfml-test/blob/92b8c02d8aa1be93076ceceb5a1a7d335e0080a6/README.txt#L12)

**Comment by lunakid** [comment]
BTW, "release packaging" is still not done; splitting it into a separate issue.
